title: Junbo Lian's Homepage
page-top-title: Junbo (Jacob) Lian
top-section-bg-text: Operations & Artificial Intelligence
home-subtitle: Junbo (Jacob) Lian&ensp;|&ensp;连俊博
copyright-text: '&copy; Junbo Lian 2024-2026. All Rights Reserved.'
